### ISSUE TITLE
implement router trait

### ISSUE THREAD

**Issue by Yuyz0112** [webzard-io/meta-ui#15]

**Comment by Sczlog** [comment]
we need two trait for the router implementation.
1. router trait:  
a router trait is going to defined target component as a routers' wrapper, which will wrap a context.provider to this component and its children. It will also provide a listener to hash/history api, schema:  
 - `id: string;` identify router itself
 - `parent: string | undefined;` id for its parent router or undefined to be a top-level router
2. route trait   
a route trait is going to defined which router the component is under, and the path it is going to match, it should support wild card matching(`/book/*`) / parameter capturing(`/book/:bookid`),schema:  
 - `path: string` the path of current route
 - `router: string` the id of its router
 - `exact: boolean` exact matching
 - `strict: boolean` strict matching
 both boolean flag's behavior will be same to the react router one.

**Comment by Yuyz0112** [comment]
The schema looks good to me. I just wondering how would the runtime be implemented.
