### ISSUE TITLE
support multiple expression in single string

### ISSUE THREAD

**Issue by Sczlog** [webzard-io/meta-ui#23]
current implementation with multiple expression:
``` 
expression: `"constantA"+{{ variableA }} + "constantB" + {{ variableB }}`
```

expected:
```
expression: `constantA{{ variableA }}constantB{{  variableB }}`
```

**Comment by Yuyz0112** [comment]
@Sczlog 
So when we are using multiple expressions, the expected behavior is to concat the result of each expression evaluation as a string?

```
{{ 100 }}+1 
```

result in
```
100+1
```

**Comment by Sczlog** [comment]
@Yuyz0112 
Yes, imo, anything not inside bracklet is considered as string.

**Comment by tanbowensg** [comment]
I list some use case

` '{{ value + 1 }}' `

101

` '{{ value.toUppercase() }}' `

'ABC'

`'Hello, {{ value }}!' `

'Hello, world'

`'{{ $listItem.name }} is {{ $listItem.age }} years old' `

'Tom is 10 years old'

` '{{ $listItem.name }} is in {{ root.listTitle }} list'`

'Tom is in UserList list'

**Comment by tanbowensg** [comment]
> @tanbowensg Good test cases 👍
> 
> In the last case, is this a valid iife?
> 
> ```js
>   function() {
>       if (value > 0) {
>         return "Option 1";
>       } else {
>         return "Option 2";
>       }
>    }()
> ```
> 
> I can only execute the following one without error
> 
> ```js
>   (function() {
>       if (value > 0) {
>         return "Option 1";
>       } else {
>         return "Option 2";
>       }
>    })()
> ```

You are right. iife should be enbraced in bracket.
