### ISSUE TITLE
new trait implementation

### ISSUE THREAD

**Issue by tanbowensg** [webzard-io/meta-ui#42]
Chinese Version: https://thoughts.teambition.com/share/6124b6fdf1962900423f2e5e

- [x] New Trait Implementation
- [x] Refactor Validation Trait
- [x] Refactor Event Trait
- [x] Refactor State Trait
- [x] Refactor Hidden Trait
- [x] Global Event Handler
- [ ] Adaptor between Component & Trait

# Why we need new implementation
1. Trait is now implemented based on executing hooks in a loop, which is not the correct usage of hooks.
2. Dynamic creating component in Trait hook will cause unnecessary mount & unmount.  see demo on branch `validation-bug`

# New implementation

1. Components will received props from Traits. Components should implement some defined capabilities of components (such as how to deal with style, data, etc.)

2. Trait is an ordinary function, not a Hook.

3. Trait accepts the parameters from the Schema, and then returns an object. This object is implemented in accordance with defined capabilities of component.

4. Merge all the objects returned by Trait and pass them to the component.

<img width="657" alt="截屏2021-08-27 上午11 25 32" src="https://user-images.githubusercontent.com/12260952/131067154-30a705c8-8e55-48c4-8215-c2fc73d398c5.png">
# Trait restrictions

1. Each component must implement some interface to interact with traits

2. Hook cannot be used in Trait (or the number of Trait cannot be changed dynamically?)
3. Cannot use HOC in Trait

# How to implement the existing Trait?

1. Hidden

     1. Return style, use display: none

1. State

     1. Return data, and the component calls mergeState to bind it to the store

1. event

     1. Return the callback function. The timing of unsubscribe is controlled by the component.

**Comment by tanbowensg** [comment]
> @tanbowensg So in the new design, a trait should only interact with components by using plain JS objects.
> 
> If some general function needs to add a UI/React element to the component, then it should be a component instead of a trait?

It can be a trait. For example, in form validation, we need a text to show error message. But the validation trait does not add a text element to input. It just merge error message to store. We need to add a text component explicitly in schema to show error message.
I'm not sure this is the best pratise so far because it will cause many template code.

**Comment by Yuyz0112** [comment]
@tanbowensg agree
