### ISSUE TITLE
Update Spec 

### ISSUE THREAD

**Issue by tanbowensg** [webzard-io/meta-ui#54]
# Component Spec
1. remove `acceptTrait`
2. add `styleSlots` and `events`. Both of them are simple string array.
```
 type Component = {
  version: string;
  kind: 'Component';
  metadata: Metadata;
  spec: ComponentSpec;
};

type ComponentSpec = {
  properties: JSONSchema;
  state: JSONSchema;
  methods: MethodSchema[];
  styleSlots: string[];
  slots: string[];
  events: string[]
};
```

# Trait Spec
1. add `returnProps`. `returnProps` are keys of the object returned by trait. For now, there are only 2 keys: `styles` and `callbackMap`. Component can only deal with these 2 props.

```
 type Trait = {
  version: string;
  kind: 'Trait';
  metadata: Metadata;
  spec: TraitSpec;
};

type TraitSpec = {
  properties: JSONSchema;
  state: JSONSchema;
  methods: MethodSchema[];
  returnProps: string[]// styles, callbackMap...
};
```

**Comment by Yuyz0112** [comment]
Another proposal: update `ComponentSpec.properties` and `TraitSpec.properties` from `JSONSchema[]` to `JSONSchema`.

**Comment by Yuyz0112** [comment]
@tanbowensg I've updated the proposal with an example. If this looks reasonable to you, I'm going to send a PR.

**Comment by tanbowensg** [comment]
Ok.LGTM. The new spec looks simpler and more precise.

**Comment by Yuyz0112** [comment]
@tanbowensg I think the original proposal of this issue still needs an update?
