### ISSUE TITLE
Toast

### ISSUE THREAD

**Issue by tanbowensg** [webzard-io/meta-ui#65]

**Comment by Yuyz0112** [comment]
Should toast work as `$util.toast` or a component?

**Comment by tanbowensg** [comment]
> Should toast work as `$util.toast` or a component?

It will be easier to use if it worked as `$util.toast`. Otherwise, there will be too many Toast components to declare. Unless we want add slot in it like Dialog, I think it doesn't have to be a component.

**Comment by Sczlog** [comment]
@Yuyz0112 
Yes, toast will be designed as a utils and controlled by a global toast manager, calling `$util.toast` will use the manager to create a toast component and handle its lifecycle.
