### ISSUE TITLE
'{{[]}}' expression causes infinite loop

### ISSUE THREAD

**Issue by tanbowensg** [webzard-io/meta-ui#68]
Because every time '{{[]}}' is evaled, a new [] will generate, so that watch function treat is as a different value then trigger callback.

By the way, '{{{}}}' cannot be parsed correctly.

**Comment by Yuyz0112** [comment]
Shall we attach a minimal app schema that can reproduce this bug to this issue?

**Comment by Sczlog** [comment]
@Yuyz0112 
create any component with state trait initialiValue with `{{[]}}`
``` javascript
{
  type: 'core/v1/state',
  properties: {
    key: 'lastToast',
    initialValue: `{{[]}}`,
  },
}
```

**Comment by Yuyz0112** [comment]
@Sczlog 

Could not reproduce the issue with a component like this

```js
{
  id: 'key_shift',
  type: 'chakra_ui/v1/kbd',
  properties: {
    text: {
      format: 'plain',
      raw: 'shift',
    },
  },
  traits: [
    {
      type: 'core/v1/slot',
      properties: {
        container: {
          id: 'root',
          slot: 'root',
        },
      },
    },
    {
      type: 'core/v1/state',
      properties: {
        key: 'infiniteLoop',
        initialValue: `{{[]}}`,
      },
    },
  ],
}
```

**Comment by Sczlog** [comment]
@Yuyz0112 It seems to be fixed in this [pr](https://github.com/webzard-io/meta-ui/pull/61/files#diff-753b7d73af7aa759573a3324fcc5d25d3dbaff2b291d3f860dee668b3a468171)

**Comment by tanbowensg** [comment]
It is a bug cuased by the life cycle. The life cycle is a little bit complex. I will introduce it at next sync meeting.
